[package]
name = "minecraft_block_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
curl = "0.4.43"
json = "0.12.4"
